services:
  app:
    build:
      context: .
      target: dev
    depends_on:
      - db
    command: npm run dev
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - /app/node_modules

  db:
    extends:
      file: docker-compose.base.yml
      service: db