services:
  app:
    build: .
    depends_on:
      - db
    command: npm run dev
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db-data:/var/lib/postgresql/data