services:
  app:
    build:
      context: .
      target: prod
    depends_on:
      - db
    command: node src/index.js
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production
      - DB_HOST=db=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DATABASE_URL=${DATABASE_URL}
  db:
    extends:
      file: docker-compose.base.yml
      service: db
  
      